package com.cradleVSA.neptune.view.ui.reading

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.Button
import androidx.databinding.DataBindingComponent
import androidx.databinding.DataBindingUtil
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.navigation.Navigation
import com.cradleVSA.neptune.R
import com.cradleVSA.neptune.binding.FragmentDataBindingComponent
import com.cradleVSA.neptune.databinding.FragmentVitalSignsBinding
import com.cradleVSA.neptune.view.ReadingActivity
import com.cradleVSA.neptune.viewmodel.PatientReadingViewModel

private const val TAG = "VitalSignsFragment"

/**
 * Allow user to input vital signs, including OCR for data from the photo.
 */
class VitalSignsFragment : Fragment() {
    /**
     * ViewModel is scoped to the [ReadingActivity] that this Fragment is attached to; therefore,
     * this is shared by all Fragments.
     */
    private val viewModel: PatientReadingViewModel by activityViewModels()

    private val dataBindingComponent: DataBindingComponent = FragmentDataBindingComponent()

    // The name "FragmentVitalSignsBinding" is generated by the Data Binding library.
    private var binding: FragmentVitalSignsBinding? = null

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        binding = DataBindingUtil.inflate(
            inflater,
            R.layout.fragment_vital_signs,
            container,
            false,
            dataBindingComponent
        )
        binding?.apply {
            lifecycleOwner = viewLifecycleOwner
            viewModel = this@VitalSignsFragment.viewModel
            executePendingBindings()
        }
        return binding?.root
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        view.findViewById<Button>(R.id.cradle_vsa_take_photo_button)?.setOnClickListener(
            Navigation.createNavigateOnClickListener(
                R.id.action_vitalSignsFragment_to_cameraXFragment,
                null
            )
        )

        // Required to observe for source updates to come to these LiveData.
        viewModel.bloodPressure.observe(viewLifecycleOwner) {}
        viewModel.urineTest.observe(viewLifecycleOwner) {}
    }

    companion object {
        const val MANUAL_USER_ENTRY_SYSTOLIC = 1
        const val MANUAL_USER_ENTRY_DIASTOLIC = 2
        const val MANUAL_USER_ENTRY_HEARTRATE = 4

        /**
         * OCR
         */
        private const val OCR_DEBUG_IDS_SCALED_IDX = 0
        private const val OCR_DEBUG_IDS_RAW_IDX = 1
        private const val OCR_DEBUG_IDS_TEXT_IDX = 2
    }
}
